# Generated by Django 3.1.4 on 2020-12-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0002_auto_20201224_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='gallery',
            field=models.URLField(blank=True),
        ),
    ]
