# Generated by Django 3.1.4 on 2020-12-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0003_auto_20201224_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news_pics')),
                ('paragraph1', models.TextField()),
                ('article', models.TextField()),
                ('gallery', models.URLField(blank=True)),
                ('present', models.BooleanField(default=False)),
            ],
        ),
    ]
