# Generated by Django 3.1.4 on 2020-12-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='event_pics')),
                ('paragraph1', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project_pics'),
        ),
    ]
