# Generated by Django 3.1.4 on 2020-12-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0005_auto_20201225_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presVolunteers', models.CharField(max_length=15)),
                ('pastVolunteers', models.CharField(max_length=15)),
                ('Projects', models.CharField(max_length=15)),
            ],
        ),
    ]
