# Generated by Django 3.1.4 on 2020-12-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0006_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
