# Generated by Django 3.1.4 on 2020-12-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0007_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='YEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='event_pics')),
                ('paragraph1', models.TextField()),
                ('forms_rules', models.URLField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aum.event')),
            ],
        ),
    ]
