# Generated by Django 3.1.4 on 2021-03-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0009_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
