# Generated by Django 3.1.4 on 2021-03-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0010_collaborator_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='contry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
