# Generated by Django 3.1.4 on 2021-04-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0011_collaborator_contry'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, upload_to='news_pics'),
        ),
        migrations.AddField(
            model_name='news',
            name='link1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='link1_prompt',
            field=models.TextField(blank=True),
        ),
    ]
