# Generated by Django 3.1.4 on 2021-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0012_auto_20210403_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='article2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, upload_to='news_pics'),
        ),
        migrations.AddField(
            model_name='project',
            name='link1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='link1_prompt',
            field=models.TextField(blank=True),
        ),
    ]
