# Generated by Django 3.1.4 on 2021-04-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0013_auto_20210404_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='gallery',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='gallery',
            new_name='album',
        ),
        migrations.AddField(
            model_name='news',
            name='hashtag',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hashtag',
            field=models.URLField(blank=True),
        ),
    ]
