# Generated by Django 3.1.4 on 2021-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0014_auto_20210404_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='yevent',
            name='album',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='yevent',
            name='hashtag',
            field=models.URLField(blank=True),
        ),
    ]
