# Generated by Django 3.1.4 on 2021-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0015_auto_20210404_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
    ]
