# Generated by Django 3.1.4 on 2021-06-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0016_auto_20210405_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='yevent',
            name='link1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='yevent',
            name='link1_prompt',
            field=models.TextField(blank=True),
        ),
    ]
